-keepattributes SourceFile, LineNumberTable
-renamesourcefileattribute

-obfuscationdictionary proguard-dictionary.txt
-packageobfuscationdictionary proguard-dictionary.txt
-classobfuscationdictionary proguard-dictionary.txt